/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.udesc.notifymenow.admin.view;

/**
 *
 * @author Wagner
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mFeedNoticias = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mCadSite = new javax.swing.JMenuItem();
        mCadAssunto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mPesquisarSite = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mHorario = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Feed de Notícias");

        mFeedNoticias.setText("Feed de Notícias");
        jMenu3.add(mFeedNoticias);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Cadastro");

        mCadSite.setText("Site");
        jMenu1.add(mCadSite);

        mCadAssunto.setText("Assunto ");
        mCadAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadAssuntoActionPerformed(evt);
            }
        });
        jMenu1.add(mCadAssunto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pesquisar");

        mPesquisarSite.setText("Site");
        jMenu2.add(mPesquisarSite);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Configurações");

        mHorario.setText("Horário de Pesquisa");
        jMenu4.add(mHorario);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCadAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadAssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCadAssuntoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem mCadAssunto;
    public javax.swing.JMenuItem mCadSite;
    public javax.swing.JMenuItem mFeedNoticias;
    public javax.swing.JMenuItem mHorario;
    public javax.swing.JMenuItem mPesquisarSite;
    // End of variables declaration//GEN-END:variables
}
